I'm really often hitting this issue where I get
    AttributeError: install_layout

in __getattr__().  I think it might be caused by some Debian-ism
but I'm not sure what is going on, because I keep getting it on
a fresh install of the official pypy's.  I usually fix it with
this "except AttributeError", which I'm now checking in.